package com.ugaap.ugaap.CollectionService.DTO;

import lombok.Data;
import java.util.List;
import java.util.UUID;

@Data
public class BatchSettlementEventDTO {
    private String batchId;             // Unique tracking reference generated by the Payment Service
    private List<UUID> clearedDeliveryIds; // The physical produce delivery ledger entries to reconcile
    private String completedAt;          // Timestamp of bank execution clearance
}