spring.application.name=eureka-server
server.port=8761

# Don't register itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.enable-self-preservation=false

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always