spring.application.name=membership-service
server.port=8082

# ---------------- CONFIG SERVER ----------------
spring.cloud.config.enabled=false

# ---------------- DATABASE ----------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=membership
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ---------------- EUREKA ----------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ---------------- LOGGING ----------------
logging.level.com.ugaap=DEBUG

# ---------------- ACTUATOR ----------------
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# ---------------- SWAGGER ----------------
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs



# ---------------- INTERNAL SERVICE COMMUNICATION ----------------
app.internal.api-key=${INTERNAL_API_KEY}

app.services.auth-service-url=http://localhost:8081

# These values should not be hardcoded(shud be like this)
# --------  app.services.auth-service-url=http://AUTHENTICATION-SERVICE -------


# Minio
app.minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
app.minio.access-key=${MINIO_ROOT_USER:minioadmin}
app.minio.secret-key=${MINIO_ROOT_PASSWORD:minioadmin}
app.minio.bucket=${MINIO_BUCKET:ugaap-images}



# ---------------- REDIS (OTP / sessions) ----------------
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=2000ms



app.jwt.secret=${JWT_SECRET:your-256-bit-secret-key-replace-this-in-production-minimum-32-chars}
app.jwt.access-token-expiry-ms=900000
app.jwt.refresh-token-expiry-ms=604800000