spring.application.name=api-gateway
server.port=8083

# Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true



# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG

# CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200,http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].max-age=3600

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# Apply this config specifically to all path patterns
spring.cloud.gateway.globalcors.cors-configurations.corsConfigs.pathPattern=/**



# Authentication Service - public auth endpoints
spring.cloud.gateway.routes[0].id=authentication-service
spring.cloud.gateway.routes[0].uri=lb://AUTHENTICATION-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Authentication Service - internal endpoints
spring.cloud.gateway.routes[1].id=authentication-service-internal
spring.cloud.gateway.routes[1].uri=lb://AUTHENTICATION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/internal/credentials/**

# Membership Service - cooperatives
spring.cloud.gateway.routes[2].id=membership-service-cooperatives
spring.cloud.gateway.routes[2].uri=lb://MEMBERSHIP-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/cooperatives/**

# Membership Service - branches
spring.cloud.gateway.routes[3].id=membership-service-branches
spring.cloud.gateway.routes[3].uri=lb://MEMBERSHIP-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/branches/**

# Membership Service - members
spring.cloud.gateway.routes[4].id=membership-service-members
spring.cloud.gateway.routes[4].uri=lb://MEMBERSHIP-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/members/**

# Membership Service - access management
spring.cloud.gateway.routes[5].id=membership-service-access
spring.cloud.gateway.routes[5].uri=lb://MEMBERSHIP-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/access/**

# Membership Service - internal endpoints
spring.cloud.gateway.routes[6].id=membership-service-internal
spring.cloud.gateway.routes[6].uri=lb://MEMBERSHIP-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/internal/users/**



# Maker-Checker setup
spring.cloud.gateway.routes[7].id=membership-maker-checker
spring.cloud.gateway.routes[7].uri=lb://MEMBERSHIP-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/maker-checker/**


# Configuration Service - grades
spring.cloud.gateway.routes[8].id=configuration-service-grades
spring.cloud.gateway.routes[8].uri=lb://CONFIGURATION-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/grades/**

# Configuration Service - prices
spring.cloud.gateway.routes[9].id=configuration-service-prices
spring.cloud.gateway.routes[9].uri=lb://CONFIGURATION-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/prices/**