spring.application.name=reconciliation
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/recon
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# JWT
app.jwt.secret=your-256-bit-secret-key-replace-this-in-production-minimum-32-chars
app.jwt.access-token-expiry-ms=900000
app.jwt.refresh-token-expiry-ms=604800000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.api-docs.path=/v3/api-docs

# Logging
logging.level.com.reconciliation=DEBUG
logging.level.org.springframework.security=INFO