spring.application.name=collection-service
server.port=8084

# Disable config server for now
spring.cloud.config.enabled=false

# PostgreSQL
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/ugaap_db
spring.datasource.username=postgres
spring.datasource.password=postgres26
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.open-in-view=false

# Jackson timezone
spring.jackson.time-zone=UTC

# ---------------- EUREKA ----------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# ---------------- LOGGING ----------------
logging.level.com.ugaap=DEBUG

# ---------------- ACTUATOR ----------------
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Inventory Service URL for automatic recovery calls
inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8087}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
