spring.application.name=collection-service
server.port=8084

# Disable config server for now
spring.cloud.config.enabled=false

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# Collection Service - farmer search
spring.cloud.gateway.routes[10].id=collection-service-farmers
spring.cloud.gateway.routes[10].uri=lb://COLLECTION-SERVICE
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/v1/farmers/**

# Collection Service - deliveries
spring.cloud.gateway.routes[11].id=collection-service-deliveries
spring.cloud.gateway.routes[11].uri=lb://COLLECTION-SERVICE
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/v1/deliveries/**


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.open-in-view=false

# Jackson timezone
spring.jackson.time-zone=UTC

# ---------------- EUREKA ----------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# ---------------- LOGGING ----------------
logging.level.com.ugaap=DEBUG

# ---------------- ACTUATOR ----------------
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Inventory Service URL for automatic recovery calls
inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8087}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
